name: drosha-gnn
channels:
- conda-forge
dependencies:
- python>=3.9
- jupyter
- jupyterlab
- ipykernel
- scipy
- numpy
- matplotlib
- seaborn
- pandas
- pip
- mamba
- ipywidgets
- networkx
- pyprojroot
- pyjanitor
- pre-commit
- black
- jax<=0.2.9
- jaxlib<=0.1.61
- typer
- pip:
  - wandb
